settings:
  title: 'Status Page'
  url: 'https://status-page.eidam.dev' # used for Slack messages
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 90 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Not All Systems Operational'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:
  - id: smoant # unique identifier
    name: smoant.com
    description: 'You write code. They handle the rest.' # default=empty
    url: 'https://smoant.com' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: true # allows the title to be a link, default=true

  - id: www-cloudflare-com
    name: clouportech
    description: 'Built for anything connected to the Internet.'
    url: 'https://www.clouportech.com'
    method: GET
    expectStatus: 200
    linkable: true # allows the title to be a link, default=true

  - id: antbarcom
    name: Antbar
    description: 'antbar website.'
    url: 'https://antbar.com'
    method: GET
    expectStatus: 200

  - id: antbar_id
    name: antbar.id
    url: 'https://antbar.id'
    method: GET
    expectStatus: 200

  - id: antbar_vn
    name: antbar.vn
    url: 'https://antbar.vn'
    method: GET
    expectStatus: 200

  - id: udnbar_com
    name: udnbar.com
    url: 'https://udnbar.com'
    method: GET
    expectStatus: 200

  - id: smoantmall_com
    name: smoantmall.com
    url: 'https://smoantmall.com'
    method: GET
    expectStatus: 200

  - id: cloupor_com
    name: cloupor.com
    url: 'https://cloupor.com'
    method: GET
    expectStatus: 200
